# Generated by Django 5.2.13 on 2026-04-24 12:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('driver', 'Driver')], default='employee', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, choices=[('car_driver', 'Car Driver'), ('bike_driver', 'Bike Driver'), ('supervisor', 'Supervisor'), ('representative', 'Representative'), ('administrative', 'Administrative'), ('hp_manager', 'HP Manager'), ('accountant', 'Accountant')], max_length=30)),
                ('identification_number', models.CharField(blank=True, max_length=50)),
                ('passport', models.CharField(blank=True, max_length=50)),
                ('contract_expiry_date', models.DateField(blank=True, null=True)),
                ('base_salary_kd', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('iban_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, choices=[('nbk', 'National Bank of Gulf (NBK)'), ('kfh', 'Gulf Finance House (KFH)'), ('gulf_bank', 'Gulf Bank'), ('burgan', 'Burgan Bank'), ('al_ahli', 'Al Ahli Bank of Gulf'), ('commercial', 'Commercial Bank of Gulf'), ('boubyan', 'Boubyan Bank'), ('other', 'Other')], max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='profile_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('civil_id_number', models.CharField(max_length=50)),
                ('civil_id_expiry', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('working_permit_expiry', models.DateField(blank=True, null=True)),
                ('driver_license_expiry', models.DateField(blank=True, null=True)),
                ('health_insurance_expiry', models.DateField(blank=True, null=True)),
                ('criminal_certificate_expiry', models.DateField(blank=True, null=True)),
                ('vehicle_registration', models.CharField(blank=True, max_length=100)),
                ('vehicle_registration_expiry', models.DateField(blank=True, null=True)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=30)),
                ('vehicle_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('motorcycle', 'Motorcycle')], default='bike', max_length=20)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('petrol_card_number', models.CharField(blank=True, max_length=50)),
                ('employee_serial_number', models.CharField(blank=True, max_length=50)),
                ('working_id', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(choices=[('najmat', 'SAYYEDNAA LOGISTICS'), ('speedy', 'Speedy'), ('other', 'Other')], default='najmat', max_length=20)),
                ('contract_type', models.CharField(choices=[('talabat', 'Talabat'), ('burger_king', 'Burger King'), ('pharmazone', 'Pharmazone'), ('other', 'Other')], default='talabat', max_length=20)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('iban_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, choices=[('nbk', 'National Bank of Gulf (NBK)'), ('kfh', 'Gulf Finance House (KFH)'), ('gulf_bank', 'Gulf Bank'), ('burgan', 'Burgan Bank'), ('al_ahli', 'Al Ahli Bank of Gulf'), ('commercial', 'Commercial Bank of Gulf'), ('boubyan', 'Boubyan Bank'), ('other', 'Other')], max_length=30)),
                ('basic_salary_wp', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='driver_docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drivers', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('deduction_date', models.DateField()),
                ('contracting_company', models.CharField(choices=[('talabat', 'Talabat'), ('burger_king', 'Burger King'), ('pharmazone', 'Pharmazone'), ('other', 'Other')], max_length=20)),
                ('contractor_deduction_kd', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('company_deduction_kd', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pdf_proof', models.FileField(blank=True, null=True, upload_to='deduction_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_deductions', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions', to='core.driver')),
            ],
            options={
                'ordering': ['-deduction_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cash', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('main_orders', models.IntegerField(default=0)),
                ('additional_orders', models.IntegerField(default=0)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('specified_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.driver')),
            ],
            options={
                'ordering': ['-specified_date'],
                'indexes': [models.Index(fields=['driver', 'specified_date'], name='core_driver_driver__f8c618_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=200)),
                ('cash', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('main_orders', models.IntegerField(default=0)),
                ('additional_orders', models.IntegerField(default=0)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('archive_date', models.DateField()),
                ('salary_slip_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='core.driver')),
            ],
            options={
                'ordering': ['-archive_date'],
                'indexes': [models.Index(fields=['driver', 'archive_date'], name='core_invoic_driver__2bad8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='core_messag_recipie_a5e560_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('document_expiry', 'Document Expiry'), ('invoice_action', 'Invoice Action'), ('new_message', 'New Message'), ('deduction', 'Deduction'), ('system', 'System')], default='system', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='core_task_user_id_d25a04_idx')],
            },
        ),
    ]
