# Generated by Django 5.2.13 on 2026-04-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deduction_is_installment_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='company_name',
            field=models.CharField(choices=[('najmat', 'SAYYEDNAA LOGISTICS'), ('speedy', 'Speedy'), ('other', 'Other')], default='najmat', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(default='Car Driver', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('motorcycle', 'Motorcycle')], default='car', max_length=20),
        ),
    ]
