# Generated by Django 5.2.13 on 2026-04-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_driver_company_name_alter_driver_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='driver',
            name='company_name',
            field=models.CharField(choices=[('najmat', 'Sayedna Logistics'), ('speedy', 'Speedy'), ('other', 'Other')], default='najmat', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(choices=[('nbk', 'National Bank of Gulf (NBK)'), ('kfh', 'Gulf Finance House (KFH)'), ('gulf_bank', 'Gulf Bank'), ('burgan', 'Burgan Bank'), ('al_ahli', 'Al Ahli Bank of Gulf'), ('commercial', 'Commercial Bank of Gulf'), ('boubyan', 'Boubyan Bank'), ('other', 'Other')], default='nbk', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('car_driver', 'Car Driver'), ('bike_driver', 'Bike Driver'), ('supervisor', 'Supervisor'), ('representative', 'Representative'), ('administrative', 'Administrative'), ('hp_manager', 'HP Manager'), ('accountant', 'Accountant')], default='administrative', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('driver', 'Driver')], default='manager', max_length=20),
        ),
    ]
