# Generated by Django 5.2.13 on 2026-04-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_avatar_alter_driver_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Administrative', 'Administrative'), ('Engineer', 'Engineer'), ('Accountant', 'Accountant'), ('Representative', 'Representative'), ('MarketingManager', 'Marketing Manager'), ('SalesManager', 'Sales Manager'), ('HRManager', 'HR Manager'), ('ProjectManager', 'Project Manager'), ('ProductManager', 'Product Manager'), ('BusinessAnalyst', 'Business Analyst'), ('SoftwareEngineer', 'Software Engineer'), ('WebDeveloper', 'Web Developer'), ('GraphicDesigner', 'Graphic Designer'), ('ContentWriter', 'Content Writer'), ('CustomerSupportRepresentative', 'Customer Support Representative'), ('DataAnalyst', 'Data Analyst'), ('OperationsManager', 'Operations Manager'), ('AdminAssistant', 'Admin Assistant'), ('TeamLeader', 'Team Leader'), ('MarketingSpecialist', 'Marketing Specialist'), ('LegalAdvisor', 'Legal Advisor'), ('ITSupportSpecialist', 'IT Support Specialist'), ('Receptionist', 'Receptionist'), ('Intern', 'Intern')], default='Administrative', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('accountant', 'Accountant'), ('driver', 'Driver')], default='manager', max_length=20),
        ),
    ]
