# Generated by Django 5.2.13 on 2026-04-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_role_companyfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverinvoice',
            unique_together={('driver', 'specified_date')},
        ),
    ]
