# Generated by Django 5.2.13 on 2026-04-29 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_deductioninstallment_paid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSalaryDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('talabat', 'Talabat'), ('burger_king', 'Burger King'), ('pharmazone', 'Pharmazone'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('absent_days', models.IntegerField(default=0)),
                ('absent_deduction', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyProfitLoss',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('contract_name', models.CharField(max_length=200)),
                ('expense', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('profit_loss', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('month', models.DateField()),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='monthly_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='TalabatSalaryDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('batch_1_orders', models.IntegerField(default=0)),
                ('batch_1_rate', models.DecimalField(decimal_places=3, default=4.5, max_digits=10)),
                ('batch_2_orders', models.IntegerField(default=0)),
                ('batch_2_rate', models.DecimalField(decimal_places=3, default=4.5, max_digits=10)),
                ('batch_3_orders', models.IntegerField(default=0)),
                ('batch_3_rate', models.DecimalField(decimal_places=3, default=4.5, max_digits=10)),
                ('batch_4_orders', models.IntegerField(default=0)),
                ('batch_4_rate', models.DecimalField(decimal_places=3, default=4.5, max_digits=10)),
                ('batch_5_orders', models.IntegerField(default=0)),
                ('batch_5_rate', models.DecimalField(decimal_places=3, default=4.5, max_digits=10)),
                ('batch_6_orders', models.IntegerField(default=0)),
                ('batch_6_rate', models.DecimalField(decimal_places=3, default=4.5, max_digits=10)),
                ('batch_7_orders', models.IntegerField(default=0)),
                ('batch_7_rate', models.DecimalField(decimal_places=3, default=4.5, max_digits=10)),
                ('deduction', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talabat_salaries', to='core.driver')),
            ],
            options={
                'ordering': ['-month', 'driver__first_name'],
                'unique_together': {('driver', 'month')},
            },
        ),
    ]
