# Generated by Django 5.2.13 on 2026-04-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contractsalarydetail_monthlyprofitloss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractsalarydetail',
            old_name='absent_days',
            new_name='absent',
        ),
        migrations.RenameField(
            model_name='contractsalarydetail',
            old_name='absent_deduction',
            new_name='deduction',
        ),
        migrations.RenameField(
            model_name='contractsalarydetail',
            old_name='salary',
            new_name='total_salary',
        ),
        migrations.RemoveField(
            model_name='talabatsalarydetail',
            name='batch_1_rate',
        ),
        migrations.RemoveField(
            model_name='talabatsalarydetail',
            name='batch_2_rate',
        ),
        migrations.RemoveField(
            model_name='talabatsalarydetail',
            name='batch_3_rate',
        ),
        migrations.RemoveField(
            model_name='talabatsalarydetail',
            name='batch_4_rate',
        ),
        migrations.RemoveField(
            model_name='talabatsalarydetail',
            name='batch_5_rate',
        ),
        migrations.RemoveField(
            model_name='talabatsalarydetail',
            name='batch_6_rate',
        ),
        migrations.RemoveField(
            model_name='talabatsalarydetail',
            name='batch_7_rate',
        ),
        migrations.AddField(
            model_name='contractsalarydetail',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_1_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_2_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_3_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_4_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_5_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_6_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_7_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
