# Generated by Django 5.2.13 on 2026-05-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_absent_days_contractsalarydetail_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='civil_id_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/civil_id/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='criminal_pcc_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/criminal_pcc/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_license_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/driving_license/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='health_card_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/health_card/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='other_docs_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/other/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/passport/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/photo/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_rc_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/vehicle_rc/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='work_permit_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/work_permit/'),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='talabat_attachments/'),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_1_net_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_2_net_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_3_net_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_4_net_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_5_net_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_6_net_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='batch_7_net_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company_name',
            field=models.CharField(choices=[('najmat', 'SAYEDNA LOGISTICS'), ('speedy', 'Speedy'), ('other', 'Other')], default='najmat', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('accountant', 'Accountant Department'), ('driver', 'Driver')], default='manager', max_length=20),
        ),
    ]
