# Generated by Django 5.2.13 on 2026-05-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_driver_civil_id_file_driver_criminal_pcc_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='talabatsalarydetail',
            options={'ordering': ['-month', 'driver__full_name']},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contractsalarydetail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contract_attachments/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='file_status',
            field=models.CharField(blank=True, default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='full_name',
            field=models.CharField(default='Seed Name', max_length=200),
            preserve_default=False,
        ),
    ]
