# Generated by Django 5.2.13 on 2026-05-04 11:56

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsalarydetail',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_salaries', to='core.driver'),
        ),
        migrations.AlterField(
            model_name='companyfile',
            name='file',
            field=models.FileField(upload_to='company_files/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='contractsalarydetail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contract_attachments/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='civil_id_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/civil_id/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='criminal_pcc_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/criminal_pcc/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/driving_license/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='health_card_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/health_card/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='other_docs_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/other/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/passport/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_rc_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/vehicle_rc/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='work_permit_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/work_permit/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('accountant', 'Accountant Department'), ('driver', 'Driver')], default='superadmin', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='profile_docs/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='talabatsalarydetail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='talabat_attachments/', validators=[core.validators.validate_file_extension]),
        ),
    ]
