# Generated by Django 6.0.4 on 2026-05-05 06:53

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contractsalarydetail_driver_alter_companyfile_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverinvoice',
            name='additional_orders',
        ),
        migrations.RemoveField(
            model_name='driverinvoice',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='invoicearchive',
            name='additional_orders',
        ),
        migrations.RemoveField(
            model_name='invoicearchive',
            name='cash',
        ),
        migrations.AddField(
            model_name='driver',
            name='received_equipments_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_docs/received_equipments/', validators=[core.validators.validate_file_extension]),
        ),
    ]
