# Generated by Django 6.0.4 on 2026-05-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_driverinvoice_additional_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverinvoice',
            name='additional_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverinvoice',
            name='cash',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicearchive',
            name='additional_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicearchive',
            name='cash',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
