# Generated by Django 6.0.4 on 2026-05-08 03:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_driverinvoice_additional_orders_driverinvoice_cash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='SAYEDNA LOGISTICS', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/', validators=[core.validators.validate_file_extension])),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AlterField(
            model_name='deduction',
            name='pdf_proof',
            field=models.FileField(blank=True, null=True, upload_to='deduction_pdfs/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='deductioninstallment',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company_name',
            field=models.CharField(choices=[('sayedna', 'SAYEDNA LOGISTICS'), ('speedy', 'Speedy'), ('other', 'Other')], default='sayedna', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/photo/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=100, verbose_name='VEHICLE REGISTRATION NUMBER'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_registration_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='VEHICLE REGISTRATION NUMBER EXPIRY'),
        ),
        migrations.AlterField(
            model_name='monthlyprofitloss',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='monthly_reports/', validators=[core.validators.validate_file_extension]),
        ),
    ]
