# Generated by Django 6.0.4 on 2026-05-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_systemsettings_alter_deduction_pdf_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='max_excel_size_mb',
            field=models.PositiveIntegerField(default=20, help_text='Maximum size for Excel files (MB)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_other_size_mb',
            field=models.PositiveIntegerField(default=1, help_text='Maximum size for other documents/images (MB)'),
        ),
    ]
