# Generated by Django 5.2.13 on 2026-05-19 04:15

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_driverreceiving'),
    ]

    operations = [
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64 signature data', null=True),
        ),
        migrations.AddField(
            model_name='talabatsalarydetail',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', validators=[core.validators.validate_file_extension]),
        ),
    ]
