# Generated by Django 5.2.13 on 2026-05-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_talabatsalarydetail_signature_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='KWD', help_text='Default currency for the company', max_length=10),
        ),
    ]
