# Generated by Django 5.2.13 on 2026-05-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_company_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='currency',
            field=models.CharField(choices=[('KWD', 'Kuwaiti Dinar (KWD)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('AED', 'UAE Dirham (AED)'), ('SAR', 'Saudi Riyal (SAR)'), ('QAR', 'Qatari Riyal (QAR)'), ('OMR', 'Omani Rial (OMR)'), ('BHD', 'Bahraini Dinar (BHD)'), ('JPY', 'Japanese Yen (JPY)'), ('CNY', 'Chinese Yuan (CNY)'), ('INR', 'Indian Rupee (INR)'), ('AUD', 'Australian Dollar (AUD)'), ('CAD', 'Canadian Dollar (CAD)'), ('SGD', 'Singapore Dollar (SGD)'), ('CHF', 'Swiss Franc (CHF)')], default='KWD', help_text='Default currency for the system', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('KWD', 'Kuwaiti Dinar (KWD)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('AED', 'UAE Dirham (AED)'), ('SAR', 'Saudi Riyal (SAR)'), ('QAR', 'Qatari Riyal (QAR)'), ('OMR', 'Omani Rial (OMR)'), ('BHD', 'Bahraini Dinar (BHD)'), ('JPY', 'Japanese Yen (JPY)'), ('CNY', 'Chinese Yuan (CNY)'), ('INR', 'Indian Rupee (INR)'), ('AUD', 'Australian Dollar (AUD)'), ('CAD', 'Canadian Dollar (CAD)'), ('SGD', 'Singapore Dollar (SGD)'), ('CHF', 'Swiss Franc (CHF)')], default='KWD', help_text='Default currency for the company', max_length=10),
        ),
    ]
