# Generated by Django 6.0.5 on 2026-05-22 09:49

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_systemsettings_currency_alter_company_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='access_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='access_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='authorized_signature_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='company',
            name='authorized_signature_only',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='company',
            name='commercial_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='company',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='company',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending_details', 'Pending Details'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending_details', max_length=20),
        ),
    ]
