# Generated by Django 6.0.5 on 2026-05-22 10:06

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_company_access_expiry_date_company_access_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='mobile_number',
            new_name='owner_mobile_number',
        ),
        migrations.AddField(
            model_name='company',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='owner_signature',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/', validators=[core.validators.validate_file_extension]),
        ),
    ]
