# Generated by Django 6.0.5 on 2026-06-05 04:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDocumentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('content_data', models.JSONField(default=dict)),
                ('is_expired_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_documents', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_documents', to='core.driver')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['creator', 'due_date'], name='core_operat_creator_7a56c8_idx')],
            },
        ),
    ]
