# Generated by Django 6.0.5 on 2026-06-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_operationdocumenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='traffic_violation',
            field=models.BooleanField(default=False),
        ),
    ]
