# Generated by Django 6.0.5 on 2026-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_deduction_traffic_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicearchive',
            name='archive_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
