# Generated by Django 6.0.5 on 2026-06-07 10:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_invoicearchive_archive_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('petrol', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('oil_change', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('repair_vehicle', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('room_rent', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('sim_recharge', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('car_rent', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('emp_salary', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_expense', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.driver')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
