# Generated by Django 5.2.13 on 2026-05-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_company_driverinvoice_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_excel_size_mb',
            field=models.PositiveIntegerField(default=20, help_text='Maximum size for Excel files (MB)'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_other_size_mb',
            field=models.PositiveIntegerField(default=1, help_text='Maximum size for other documents/images (MB)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company_name',
            field=models.CharField(choices=[('sayedna', 'UNPREDICTABLE LOGISTICS SOLUTIONS'), ('speedy', 'Speedy'), ('other', 'Other')], default='sayedna', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='brand_name',
            field=models.CharField(default='UNPREDICTABLE LOGISTICS SOLUTIONS', max_length=100),
        ),
    ]
