# Generated by Django 5.2.13 on 2026-05-19 04:03

import core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_company_max_excel_size_mb_company_max_other_size_mb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverReceiving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('car', 'Car'), ('mobile_phone', 'Mobile Phone'), ('sim_card', 'SIM Card'), ('custom', 'Custom Document/Item')], max_length=20)),
                ('custom_label', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(upload_to='driver_receivings/', validators=[core.validators.validate_file_extension])),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivings', to='core.driver')),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
    ]
